// duaData.ts

export interface Dua {
  id: number;
  title: string;
  arabic: string;
  urdu: string;
  english: string;
  category: string;
  ref: string;
}

export const DUA_DATA: Dua[] = [
  {
    id: 1,
    title: "Relief from Difficulties (Ayah Kareema)",
    arabic: "لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    urdu: "تیرے سوا کوئی معبود نہیں، تو پاک ہے، بے شک میں ہی ظالموں میں سے تھا۔",
    english: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.",
    category: "Protection",
    ref: "Surah Al-Anbiya 21:87",
  },
  {
    id: 2,
    title: "Protection from All Harm",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    urdu: "اللہ کے نام کے ساتھ، جس کے نام کی برکت سے زمین اور آسمان میں کوئی چیز نقصان نہیں پہنچا سکتی، اور وہ خوب سننے والا، جاننے والا ہے۔",
    english: "In the Name of Allah, with whose Name nothing can cause harm in the earth or in the heavens, and He is the All-Hearing, the All-Knowing.",
    category: "Protection",
    ref: "Sunan Abi Dawood 5088 | Sahih",
  },
  {
    id: 3,
    title: "Refuge in Allah's Perfect Words",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    urdu: "میں اللہ کے مکمل کلمات کے ذریعے اس کی پیدا کردہ تمام مخلوقات کے شر سے پناہ مانگتا ہوں۔",
    english: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    category: "Protection",
    ref: "Sahih Muslim 2708",
  },
  {
    id: 4,
    title: "Comprehensive Protection & Well-Being",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
    urdu: "اے اللہ! میں تجھ سے دنیا اور آخرت میں معافی اور عافیت و سلامتی کا سوال کرتا ہوں۔",
    english: "O Allah, I ask You for pardon and well-being in this world and the Hereafter.",
    category: "Peace of Mind",
    ref: "Sunan Ibn Majah 3849 | Sahih",
  },
  {
    id: 5,
    title: "Supplication for a Steadfast Heart",
    arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ",
    urdu: "اے دلوں کو پھیرنے والے! میرے دل کو اپنے دین پر ثابت قدم رکھ۔",
    english: "O Turner of the hearts, make my heart firm upon Your religion.",
    category: "Peace of Mind",
    ref: "Jami` at-Tirmidhi 2140 | Hasan",
  },
  {
    id: 6,
    title: "Relief from Anxiety and Sorrow",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْجُبْنِ وَالْبُخْلِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
    urdu: "اے اللہ! میں غم، پریشانی، عاجزی، سستی، بزدلی، کنجوسی، قرض کے بوجھ اور لوگوں کے دباؤ سے تیری پناہ مانگتا ہوں۔",
    english: "O Allah, I seek refuge in You from grief, anxiety, incapacity, laziness, cowardice, miserliness, the burden of debt and overpowering of men.",
    category: "Peace of Mind",
    ref: "Sahih al-Bukhari 6369",
  },
  {
    id: 7,
    title: "Tranquility of the Heart",
    arabic: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
    urdu: "یاد رکھو! اللہ کے ذکر ہی سے دلوں کو اطمینان اور سکون حاصل ہوتا ہے۔",
    english: "Unquestionably, by the remembrance of Allah hearts are assured.",
    category: "Peace of Mind",
    ref: "Surah Ar-Ra'd 13:28",
  },
  {
    id: 8,
    title: "Seeking Beneficial Knowledge & Success",
    arabic: "رَّبِّ زِدْنِي عِلْمًا",
    urdu: "اے میرے پروردگار! میرے علم میں مزید اضافہ فرما۔",
    english: "My Lord, increase me in knowledge.",
    category: "Success",
    ref: "Surah Taha 20:114",
  },
  {
    id: 9,
    title: "Dua for Ease in Every Task",
    arabic: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا",
    urdu: "اے اللہ! کوئی کام آسان نہیں سوائے اس کے جسے تو آسان بنا دے، اور تو جب چاہے مشکل کو آسان کر دیتا ہے۔",
    english: "O Allah, there is no ease other than what You make easy, and You make hardship easy if You will.",
    category: "Success",
    ref: "Sahih Ibn Hibban 974",
  },
  {
    id: 10,
    title: "Relying Upon Allah (Tawakkul)",
    arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    urdu: "ہمیں اللہ ہی کافی ہے اور وہ بہترین کارساز ہے۔",
    english: "Sufficient for us is Allah, and [He is] the best Disposer of affairs.",
    category: "Success",
    ref: "Surah Ali 'Imran 3:173",
  },
  {
    id: 11,
    title: "Sayyid al-Istighfar (Chief of Forgiveness)",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    urdu: "اے اللہ! تو ہی میرا رب ہے، تیرے سوا کوئی معبود نہیں۔ تو نے مجھے پیدا کیا اور میں تیرا بندہ ہوں، اور میں اپنی طاقت کے مطابق تیرے عہد پر قائم ہوں۔ میں اپنے گناہوں کا اعتراف کرتا ہوں اور تیری نعمتوں کا شکر گزار ہوں، پس مجھے بخش دے کیونکہ تیرے سوا کوئی گناہوں کو معاف نہیں کر سکتا۔",
    english: "O Allah, You are my Lord, none has the right to be worshiped but You created me and I am Your slave. I abide by Your covenant and promise as best I can. Forgive me, for none forgives sins except You.",
    category: "Forgiveness",
    ref: "Sahih al-Bukhari 6306",
  },
  {
    id: 12,
    title: "Dua for Parents and Family",
    arabic: "رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ",
    urdu: "اے ہمارے پروردگار! مجھے، میرے والدین کو اور تمام مومنوں کو اس دن بخش دینا جس دن حساب قائم ہوگا۔",
    english: "Our Lord, forgive me and my parents and the believers the Day the account is established.",
    category: "Forgiveness",
    ref: "Surah Ibrahim 14:41",
  },
  {
    id: 13,
    title: "Dua for Guidance and Righteousness",
    arabic: "اللَّهُمَّ اهْدِنِي وَسَدِّدْنِي",
    urdu: "اے اللہ! مجھے سیدھی راہ کی ہدایت عطا فرما اور مجھے درست راہ پر ثابت قدم رکھ۔",
    english: "O Allah, guide me and keep me steadfast on the right path.",
    category: "Guidance",
    ref: "Sahih Muslim 2725",
  },
  {
    id: 14,
    title: "Supplication for Success in Both Worlds",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    urdu: "اے ہمارے رب! ہمیں دنیا میں بھی بھلائی عطا فرما اور آخرت میں بھی بھلائی عطا فرما اور ہمیں آگ کے عذاب سے بچا۔",
    english: "Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.",
    category: "Success",
    ref: "Surah Al-Baqarah 2:201",
  },
  {
    id: 15,
    title: "Dua When Leaving the House",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    urdu: "اللہ کے نام سے، میں نے اللہ پر بھروسہ کیا، گناہوں سے بچنے کی طاقت اور نیکی کرنے کی قوت صرف اللہ ہی کی مدد سے ہے۔",
    english: "In the name of Allah, I place my trust in Allah; there is no might nor power except with Allah.",
    category: "Protection",
    ref: "Sunan Abi Dawood 5095 | Sahih",
  },
  {
    id: 16,
    title: "Dua for Sincere Repentance",
    arabic: "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ",
    urdu: "اے میرے پروردگار! میری مغفرت فرما اور میری توبہ قبول فرما، بے شک تو ہی توبہ قبول کرنے والا، نہایت رحم فرمانے والا ہے۔",
    english: "My Lord, forgive me and accept my repentance. Indeed, You are the Accepter of repentance, the Most Merciful.",
    category: "Forgiveness",
    ref: "Sunan Abi Dawood 1516 | Sahih",
  },
];
