export interface CollectionTrack {
  surahNumber: number;
  englishName: string;
  name: string;
  englishTranslation: string;
  ayahCount: number;
  revelationType: "Meccan" | "Medinan";
  note?: string;
}

export interface CollectionItem {
  id: string;
  title: string;
  arabicTitle: string;
  urduTitle: string;
  tagline: string;
  description: string;
  badge: string;
  variant: "focus" | "sleep" | "ruqyah" | "emotional" | "melodic" | "morning" | "anxiety" | "tawbah";
  tracks: CollectionTrack[];
}

export const COLLECTIONS_DATA: CollectionItem[] = [
  {
    id: "focus-work",
    title: "Focus & Work",
    arabicTitle: "التَّرْكِيزُ وَالْعَمَلُ",
    urduTitle: "گہرا فوکس اور مطالعہ",
    tagline: "Calm, steady recitations for high focus, coding & study sessions.",
    description: "Immerse your mind in soothing, rhythmic Quranic recitations designed to eliminate distractions and bring deep focus and divine barakah into your work.",
    badge: "Productivity",
    variant: "focus",
    tracks: [
      {
        surahNumber: 18,
        englishName: "Al-Kahf",
        name: "الكهف",
        englishTranslation: "The Cave",
        ayahCount: 110,
        revelationType: "Meccan",
        note: "Light between two Fridays, deep focus and wisdom",
      },
      {
        surahNumber: 55,
        englishName: "Ar-Rahman",
        name: "الرحمن",
        englishTranslation: "The Beneficent",
        ayahCount: 78,
        revelationType: "Medinan",
        note: "Harmonious rhythm and divine blessings",
      },
      {
        surahNumber: 67,
        englishName: "Al-Mulk",
        name: "الملك",
        englishTranslation: "The Sovereignty",
        ayahCount: 30,
        revelationType: "Meccan",
        note: "Contemplation on the majesty of creation",
      },
      {
        surahNumber: 20,
        englishName: "Taha",
        name: "طه",
        englishTranslation: "Ta-Ha",
        ayahCount: 135,
        revelationType: "Meccan",
        note: "Ease in affairs, removing chest tightness",
      },
      {
        surahNumber: 19,
        englishName: "Maryam",
        name: "مريم",
        englishTranslation: "Mary",
        ayahCount: 98,
        revelationType: "Meccan",
        note: "Gentle solace and profound tranquility",
      },
    ],
  },
  {
    id: "most-beautiful",
    title: "Most Beautiful Recitations",
    arabicTitle: "أَجْمَلُ التِّلَاوَاتِ",
    urduTitle: "خوبصورت ترین تلاوتیں",
    tagline: "Heart-melting Maqamat and the most melodic Quranic recitations.",
    description: "A handpicked selection of the most melodious, soulful, and awe-inspiring Quran recitations from the Islamic world's master Qaris.",
    badge: "Masterpieces",
    variant: "melodic",
    tracks: [
      {
        surahNumber: 55,
        englishName: "Ar-Rahman",
        name: "الرحمن",
        englishTranslation: "The Beneficent",
        ayahCount: 78,
        revelationType: "Medinan",
        note: "The bride of the Quran (Aroos al-Quran)",
      },
      {
        surahNumber: 19,
        englishName: "Maryam",
        name: "مريم",
        englishTranslation: "Mary",
        ayahCount: 98,
        revelationType: "Meccan",
        note: "Sublime emotional tones of mercy",
      },
      {
        surahNumber: 50,
        englishName: "Qaaf",
        name: "ق",
        englishTranslation: "Qaf",
        ayahCount: 45,
        revelationType: "Meccan",
        note: "Majestic description of resurrection and nature",
      },
      {
        surahNumber: 76,
        englishName: "Al-Insaan",
        name: "الإنسان",
        englishTranslation: "Man",
        ayahCount: 31,
        revelationType: "Medinan",
        note: "Vivid depiction of Paradise and serenity",
      },
      {
        surahNumber: 53,
        englishName: "An-Najm",
        name: "النجم",
        englishTranslation: "The Star",
        ayahCount: 62,
        revelationType: "Meccan",
        note: "The celestial journey of Miraj",
      },
    ],
  },
  {
    id: "sleep-mode",
    title: "Sleep Mode",
    arabicTitle: "النَّوْمُ وَالسَّكِينَةُ",
    urduTitle: "گہری نیند اور رات کا سکون",
    tagline: "Soft, tranquil recitations to calm nighttime thoughts and bring peaceful sleep.",
    description: "Release daily anxiety and prepare your heart for restful, protected sleep with the prophetic bedtime Surahs.",
    badge: "Night Peace",
    variant: "sleep",
    tracks: [
      {
        surahNumber: 32,
        englishName: "As-Sajdah",
        name: "السجدة",
        englishTranslation: "The Prostration",
        ayahCount: 30,
        revelationType: "Meccan",
        note: "Prophetic Sunnah to recite before sleeping",
      },
      {
        surahNumber: 67,
        englishName: "Al-Mulk",
        name: "الملك",
        englishTranslation: "The Sovereignty",
        ayahCount: 30,
        revelationType: "Meccan",
        note: "Protection from punishment and tranquil rest",
      },
      {
        surahNumber: 56,
        englishName: "Al-Waaqia",
        name: "الواقعة",
        englishTranslation: "The Inevitable",
        ayahCount: 96,
        revelationType: "Meccan",
        note: "Spiritual abundance & remembrance of the Hereafter",
      },
      {
        surahNumber: 112,
        englishName: "Al-Ikhlaas",
        name: "الإخلاص",
        englishTranslation: "Sincerity",
        ayahCount: 4,
        revelationType: "Meccan",
        note: "Equivalent to one-third of the Quran",
      },
      {
        surahNumber: 113,
        englishName: "Al-Falaq",
        name: "الفلق",
        englishTranslation: "The Dawn",
        ayahCount: 5,
        revelationType: "Meccan",
        note: "Shelter from nightly darkness & envy",
      },
      {
        surahNumber: 114,
        englishName: "An-Naas",
        name: "الناس",
        englishTranslation: "Mankind",
        ayahCount: 6,
        revelationType: "Meccan",
        note: "Refuge from whisperings and anxiety",
      },
    ],
  },
  {
    id: "duaa-and-ruqia",
    title: "Duaa & Ruqia",
    arabicTitle: "الرُّقْيَةُ وَالشِّفَاءُ",
    urduTitle: "شفاء، دم اور حفاظت",
    tagline: "Spiritual armor for healing, warding off evil eye and protection.",
    description: "The core foundational verses of Ruqyah Shari'ah for physical and spiritual shifa, shielding your family and home under divine protection.",
    badge: "Healing Shield",
    variant: "ruqyah",
    tracks: [
      {
        surahNumber: 1,
        englishName: "Al-Faatiha",
        name: "الفاتحة",
        englishTranslation: "The Opening",
        ayahCount: 7,
        revelationType: "Meccan",
        note: "The Mother of the Book & Supreme Healer (Ash-Shifa)",
      },
      {
        surahNumber: 2,
        englishName: "Al-Baqarah",
        name: "البقرة",
        englishTranslation: "The Cow",
        ayahCount: 286,
        revelationType: "Medinan",
        note: "No negative energy can remain in a home where it is recited",
      },
      {
        surahNumber: 112,
        englishName: "Al-Ikhlaas",
        name: "الإخلاص",
        englishTranslation: "Sincerity",
        ayahCount: 4,
        revelationType: "Meccan",
        note: "Complete refuge in the One God",
      },
      {
        surahNumber: 113,
        englishName: "Al-Falaq",
        name: "الفلق",
        englishTranslation: "The Dawn",
        ayahCount: 5,
        revelationType: "Meccan",
        note: "Protection from malice, envy and witchcraft",
      },
      {
        surahNumber: 114,
        englishName: "An-Naas",
        name: "الناس",
        englishTranslation: "Mankind",
        ayahCount: 6,
        revelationType: "Meccan",
        note: "Protection from unseen whispering devils",
      },
    ],
  },
  {
    id: "emotional-healing",
    title: "Emotional Healing",
    arabicTitle: "شِفَاءُ الْقُلُوبِ",
    urduTitle: "غم کا مداوا اور دل کا سکون",
    tagline: "Comforting divine messages when feeling heartbroken, grieving or lonely.",
    description: "Whenever the weight of grief or loneliness feels heavy, let the deeply consoling verses of Allah remind you that you are never alone.",
    badge: "Solace",
    variant: "emotional",
    tracks: [
      {
        surahNumber: 93,
        englishName: "Ad-Dhuhaa",
        name: "الضحى",
        englishTranslation: "The Morning Hours",
        ayahCount: 11,
        revelationType: "Meccan",
        note: "'Your Lord has not abandoned you, nor is He displeased'",
      },
      {
        surahNumber: 94,
        englishName: "Ash-Sharh",
        name: "الشرح",
        englishTranslation: "The Relief",
        ayahCount: 8,
        revelationType: "Meccan",
        note: "'Indeed, with hardship will come ease'",
      },
      {
        surahNumber: 12,
        englishName: "Yusuf",
        name: "يوسف",
        englishTranslation: "Joseph",
        ayahCount: 111,
        revelationType: "Meccan",
        note: "The timeless story of patience, beauty and reunion",
      },
      {
        surahNumber: 14,
        englishName: "Ibrahim",
        name: "إبراهيم",
        englishTranslation: "Abraham",
        ayahCount: 52,
        revelationType: "Meccan",
        note: "Steadfast faith through life's trials",
      },
      {
        surahNumber: 13,
        englishName: "Ar-Ra'd",
        name: "الرعد",
        englishTranslation: "The Thunder",
        ayahCount: 43,
        revelationType: "Medinan",
        note: "'By the remembrance of Allah do hearts find rest'",
      },
    ],
  },
  {
    id: "morning-barakah",
    title: "Morning Barakah",
    arabicTitle: "بَرَكَةُ الصَّبَاحِ",
    urduTitle: "صبح کی برکت اور تازگی",
    tagline: "Energizing recitations to start your day with gratitude, strength & optimism.",
    description: "Begin your morning with uplifting, majestic surahs that fill your soul with radiant energy, positivity, and high spiritual resolve.",
    badge: "Morning Vitality",
    variant: "morning",
    tracks: [
      {
        surahNumber: 36,
        englishName: "Yaseen",
        name: "يس",
        englishTranslation: "Ya-Sin",
        ayahCount: 83,
        revelationType: "Meccan",
        note: "The heart of the Quran for fulfillment of daily needs",
      },
      {
        surahNumber: 48,
        englishName: "Al-Fath",
        name: "الفتح",
        englishTranslation: "The Victory",
        ayahCount: 29,
        revelationType: "Medinan",
        note: "Glad tidings of triumph and serenity",
      },
      {
        surahNumber: 55,
        englishName: "Ar-Rahman",
        name: "الرحمن",
        englishTranslation: "The Beneficent",
        ayahCount: 78,
        revelationType: "Medinan",
        note: "Gratitude for life, health and intellect",
      },
      {
        surahNumber: 57,
        englishName: "Al-Hadid",
        name: "الحديد",
        englishTranslation: "The Iron",
        ayahCount: 29,
        revelationType: "Medinan",
        note: "Glorification of Allah, the First and the Last",
      },
    ],
  },
  {
    id: "overcoming-anxiety",
    title: "Overcoming Anxiety",
    arabicTitle: "الْأَمْنُ وَالتَّوَكُّلُ",
    urduTitle: "خوف اور بے چینی سے نجات",
    tagline: "Empowering verses of Tawakkul to conquer fear, stress and uncertainty.",
    description: "Anchor your heart in times of panic or fear of the future with these mighty verses reminding that Allah suffices as our best protector.",
    badge: "Courage & Tawakkul",
    variant: "anxiety",
    tracks: [
      {
        surahNumber: 2,
        englishName: "Al-Baqarah",
        name: "البقرة",
        englishTranslation: "The Cow",
        ayahCount: 286,
        revelationType: "Medinan",
        note: "'Indeed we belong to Allah, and to Him we shall return'",
      },
      {
        surahNumber: 3,
        englishName: "Aal-i-Imraan",
        name: "آل عمران",
        englishTranslation: "The Family of Imraan",
        ayahCount: 200,
        revelationType: "Medinan",
        note: "'Sufficient for us is Allah, and He is the best Disposer of affairs'",
      },
      {
        surahNumber: 9,
        englishName: "At-Tawba",
        name: "التوبة",
        englishTranslation: "The Repentance",
        ayahCount: 129,
        revelationType: "Medinan",
        note: "'Do not grieve; indeed Allah is with us'",
      },
      {
        surahNumber: 21,
        englishName: "Al-Anbiyaa",
        name: "الأنبياء",
        englishTranslation: "The Prophets",
        ayahCount: 112,
        revelationType: "Meccan",
        note: "Dua of Prophet Yunus (A.S) from the deep sea",
      },
    ],
  },
  {
    id: "tawbah-mercy",
    title: "Tawbah & Divine Mercy",
    arabicTitle: "التَّوْبَةُ وَالْمَغْفِرَةُ",
    urduTitle: "توبہ، استغفار اور رحمت",
    tagline: "Deeply moving verses of hope, forgiveness and returning sincerely to Allah.",
    description: "Never despair of the infinite mercy of Allah. These heart-melting passages open the door of sincere repentance and wash away burdens.",
    badge: "Mercy & Renewal",
    variant: "tawbah",
    tracks: [
      {
        surahNumber: 39,
        englishName: "Az-Zumar",
        name: "الزمر",
        englishTranslation: "The Crowds",
        ayahCount: 75,
        revelationType: "Meccan",
        note: "'Do not despair of the mercy of Allah; indeed Allah forgives all sins'",
      },
      {
        surahNumber: 66,
        englishName: "At-Tahrim",
        name: "التحريم",
        englishTranslation: "The Prohibition",
        ayahCount: 12,
        revelationType: "Medinan",
        note: "Call to sincere repentance (Tawbatan Nasuha)",
      },
      {
        surahNumber: 25,
        englishName: "Al-Furqaan",
        name: "الفرقان",
        englishTranslation: "The Criterion",
        ayahCount: 77,
        revelationType: "Meccan",
        note: "The noble qualities of the servants of the Most Merciful",
      },
      {
        surahNumber: 40,
        englishName: "Ghafir",
        name: "غافر",
        englishTranslation: "The Forgiver",
        ayahCount: 85,
        revelationType: "Meccan",
        note: "The Acceptor of repentance, the Supreme Lord",
      },
    ],
  },
];
