export interface Reciter {
  id: string; // API edition identifier or EveryAyah ID
  name: string;
  arabicName: string;
  city: string;
  country: string;
  countryCode: string;
  flag: string;
  style: string;
  image: string;
  bio: string;
  totalSurahs: number;
}

export const RECITERS_LIST: Reciter[] = [
  // --- KUWAIT ---
  {
    id: "ar.alafasy",
    name: "Mishary Rashid Alafasy",
    arabicName: "مشاري راشد العفاسي",
    city: "Kuwait City",
    country: "Kuwait",
    countryCode: "kw",
    flag: "🇰🇼",
    style: "Melodic Murattal",
    image: "/reciters/mishard.jpg",
    bio: "Grand Mosque of Kuwait Imam, globally beloved for melodic and soulful recitation.",
    totalSurahs: 114,
  },

  // --- EGYPT ---
  {
    id: "ar.abdulbasitmurattal",
    name: "Abdul Basit Abdul Samad",
    arabicName: "عبد الباسط عبد الصمد",
    city: "Cairo / Luxor",
    country: "Egypt",
    countryCode: "eg",
    flag: "🇪🇬",
    style: "Murattal & Mujawwad",
    image: "/reciters/abdul.jpg",
    bio: "The 'Golden Voice' of the Muslim world and one of the greatest reciters in history.",
    totalSurahs: 114,
  },
  {
    id: "ar.minshawi",
    name: "Muhammad Siddiq Al-Minshawi",
    arabicName: "محمد صديق المنشاوي",
    city: "Sohag / Cairo",
    country: "Egypt",
    countryCode: "eg",
    flag: "🇪🇬",
    style: "Soulful Murattal",
    image: "/reciters/minshawi_v2.jpg",
    bio: "Legendary Egyptian reciter revered for heart-touching Maqamat and spiritual emotion.",
    totalSurahs: 114,
  },
  {
    id: "ar.husary",
    name: "Mahmoud Khalil Al-Husary",
    arabicName: "محمود خليل الحصري",
    city: "Tanta / Cairo",
    country: "Egypt",
    countryCode: "eg",
    flag: "🇪🇬",
    style: "Precision Tajweed",
    image: "/reciters/husary_v2.jpg",
    bio: "The pioneer of exact Tajweed rules and Quranic phonetic perfection.",
    totalSurahs: 114,
  },
  {
    id: "ar.muhammadjibreel",
    name: "Muhammad Jibreel",
    arabicName: "محمد جبريل",
    city: "Cairo",
    country: "Egypt",
    countryCode: "eg",
    flag: "🇪🇬",
    style: "Emotional Dua & Murattal",
    image: "/reciters/jibreel_v2.jpg",
    bio: "Famous Egyptian reciter and Imam of Amr ibn al-Aas Mosque in Cairo.",
    totalSurahs: 114,
  },

  // --- SAUDI ARABIA (9 RECITERS) ---
  {
    id: "ar.mahermuaiqly",
    name: "Maher Al-Muaiqly",
    arabicName: "ماهر المعيقلي",
    city: "Makkah Al-Mukarramah",
    country: "Saudi Arabia",
    countryCode: "sa",
    flag: "🇸🇦",
    style: "Imam Masjid al-Haram",
    image: "/reciters/muaiqly_v2.jpg",
    bio: "Chief Imam of the Grand Mosque (Masjid al-Haram) in Makkah al-Mukarramah.",
    totalSurahs: 114,
  },
  {
    id: "ar.abdurrahmaansudais",
    name: "Abdur-Rahman As-Sudais",
    arabicName: "عبد الرحمن السديس",
    city: "Makkah Al-Mukarramah",
    country: "Saudi Arabia",
    countryCode: "sa",
    flag: "🇸🇦",
    style: "Head Imam Masjid al-Haram",
    image: "/reciters/sudais_v2.jpg",
    bio: "President of the Two Holy Mosques Affairs and renowned Imam of Masjid al-Haram.",
    totalSurahs: 114,
  },
  {
    id: "ar.saoodshuraym",
    name: "Saud Al-Shuraim",
    arabicName: "سعود الشريم",
    city: "Makkah Al-Mukarramah",
    country: "Saudi Arabia",
    countryCode: "sa",
    flag: "🇸🇦",
    style: "Imam Masjid al-Haram",
    image: "/reciters/shuraim_v2.jpg",
    bio: "Former Imam & Khateeb of Masjid al-Haram, beloved worldwide for resonant recitation.",
    totalSurahs: 114,
  },
  {
    id: "ar.yasseraldossari",
    name: "Yasser Al-Dossari",
    arabicName: "ياسر الدوسري",
    city: "Riyadh / Makkah",
    country: "Saudi Arabia",
    countryCode: "sa",
    flag: "🇸🇦",
    style: "Imam Masjid al-Haram",
    image: "/reciters/yasser.jpg",
    bio: "Imam of Masjid al-Haram known for powerful, emotionally captivating recitation.",
    totalSurahs: 114,
  },
  {
    id: "ar.hudhaify",
    name: "Ali Al-Hudhaify",
    arabicName: "علي بن عبد الرحمن الحذيفي",
    city: "Madinah Al-Munawwarah",
    country: "Saudi Arabia",
    countryCode: "sa",
    flag: "🇸🇦",
    style: "Imam Masjid an-Nabawi",
    image: "/reciters/hudhaify_v2.jpg",
    bio: "Chief Imam of the Prophet's Mosque (Masjid an-Nabawi) in Madinah al-Munawwarah.",
    totalSurahs: 114,
  },
  {
    id: "ar.shaatree",
    name: "Abu Bakr Al-Shatri",
    arabicName: "أبو بكر الشاطري",
    city: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "sa",
    flag: "🇸🇦",
    style: "Melodious Murattal",
    image: "/reciters/shatri_v2.jpg",
    bio: "Beloved Saudi reciter known for calm, melodious cadence and distinctive voice.",
    totalSurahs: 114,
  },
  {
    id: "ar.ahmedajamy",
    name: "Ahmad Al-Ajmy",
    arabicName: "أحمد بن علي العجمي",
    city: "Khobar",
    country: "Saudi Arabia",
    countryCode: "sa",
    flag: "🇸🇦",
    style: "Soulful Murattal",
    image: "/reciters/ajmy_v2.jpg",
    bio: "World-famous Saudi reciter with an emotional, deeply moving recitation style.",
    totalSurahs: 114,
  },
  {
    id: "ar.muhammadayyoub",
    name: "Muhammad Ayyoub",
    arabicName: "محمد أيوب",
    city: "Madinah Al-Munawwarah",
    country: "Saudi Arabia",
    countryCode: "sa",
    flag: "🇸🇦",
    style: "Imam Masjid an-Nabawi",
    image: "/reciters/ayyoub_v2.jpg",
    bio: "Legendary former Imam of Masjid an-Nabawi with a timeless Hijazi recitation style.",
    totalSurahs: 114,
  },
  {
    id: "ar.hanirifai",
    name: "Hani Ar-Rifai",
    arabicName: "هاني الرفاعي",
    city: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "sa",
    flag: "🇸🇦",
    style: "Soulful & Touching",
    image: "/reciters/rifai_v2.jpg",
    bio: "Renowned Imam of Anani Mosque in Jeddah, famous for tearful emotional recitation.",
    totalSurahs: 114,
  },

  // --- SYRIA ---
  {
    id: "ar.aymanswoaid",
    name: "Ayman Sowaid",
    arabicName: "أيمن سويد",
    city: "Damascus",
    country: "Syria",
    countryCode: "sy",
    flag: "🇸🇾",
    style: "Master of Tajweed",
    image: "/reciters/sowaid_v2.jpg",
    bio: "World authority in Tajweed and Quranic readings with crystal-clear phonetic articulation.",
    totalSurahs: 114,
  },
];
